# Generated by Django 4.2.7 on 2026-05-01 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_employees', models.IntegerField(default=0)),
                ('present_count', models.IntegerField(default=0)),
                ('absent_count', models.IntegerField(default=0)),
                ('leave_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Attendance Summary',
                'verbose_name_plural': 'Attendance Summaries',
                'db_table': 'attendance_summary',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('attendance_id', models.AutoField(db_column='attendance_id', primary_key=True, serialize=False)),
                ('employee_id', models.CharField(max_length=20)),
                ('attendance_date', models.DateField()),
            ],
            options={
                'db_table': 'attendance',
                'ordering': ['-attendance_date'],
                'unique_together': {('employee_id', 'attendance_date')},
            },
        ),
    ]
